### ISSUE TITLE
Possible issue parsing UTF8 content

### ISSUE THREAD

**Issue by sam159** [for-GET/api-pegjs#2]
The below request throws a PEG exception

```
HTTP/1.1 200 OK
ETag: "QRTckq4u__VeZS8s-Were-ojNBg/w-6pnXCYSzRBOmMWOudWT6wvqZs"
Content-Type: application/json; charset=UTF-8
Date: Mon, 16 Mar 2015 12:06:40 GMT
Expires: Mon, 16 Mar 2015 12:06:40 GMT
Cache-Control: private, max-age=0
Content-Length: 318

{
 "id": "14c09c65c22f20a7",
 "threadId": "14c08f9685a4f184",
 "labelIds": [
  "Label_322"
 ],
 "snippet": "Hi Darren. Now received response from TPI engineers. They states “Blend times are 6wu to handles = £",
 "historyId": "12852897",
 "payload": {
  "mimeType": "multipart/mixed"
 },
 "sizeEstimate": 23937503
}
```

The Exception: SyntaxError (line 17 char 79): Expected [\x00-\xFF] or end of input but "\u201C" found.

Not sure if its to-do with how I'm passing the data around, will update if I make any progress.

Sam

**Comment by sam159** [comment]
Update

I'm now passing the data in as a buffer rather than a string, and seems to be working.

**Comment by andreineculau** [comment]
@sam159 

an HTTP message body is defined as follows:

```
// https://github.com/for-GET/core-pegjs/blob/master/src/ietf/draft-ietf-httpbis-p1-messaging.pegjs#L233
/* http://tools.ietf.org/html/draft-ietf-httpbis-p1-messaging#section-3.3 Message Body */
message_body
  = $(OCTET*)

// https://github.com/for-GET/core-pegjs/blob/master/src/ietf/rfc5234-core-abnf.pegjs#L53
OCTET
  = [\x00-\xFF]
```

When you use a buffer, most probably the `“` character gets escaped to `\u201c` (literally), and thus the parser is ok with that.

**Comment by andreineculau** [comment]
Curious: how are you using api-pegjs, @sam159 ?

**Comment by sam159** [comment]
I'm using it to process a multipart http response from googles batch api (https://developers.google.com/gmail/api/guides/batch).

**Comment by andreineculau** [comment]
@sam159 cool. I was going to suggest https://github.com/for-GET/literate-http but api-pegjs matches your needs closer.
